fixbug of post-action script; fixbug of ssr decode; fixbug of old version jq param of vmess; update haproxy balance

diff --git a/protocols/decode-ssr b/protocols/decode-ssr
--- a/protocols/decode-ssr
+++ b/protocols/decode-ssr
@@ -1,7 +1,17 @@
 #!/bin/bash
 ####################################
-#ssr://server:port:protocol:method:obfs:password_base64/?params_base64
-#	params_base64: obfsparam=obfsparam_base64&protoparam=protoparam_base64&remarks=remarks_base64&group=group_base64
+#ssr://server:port:protocol:method:obfs:password_base64/?params_context
+#
+#params_context:
+#	obfsparam=obfsparam_base64&protoparam=protoparam_base64&remarks=remarks_base64&group=group_base64
+#params_base64:
+#	(params_context | base64)
+#
+#EncodeType1:
+#	(server:port:protocol:method:obfs:password_base64/?params_base64) | base64
+#
+#EncodeType2:
+#	(server:port:protocol:method:obfs:password_base64/?params_context) | base64
 #
 #CMD:
 #	ssr-local -l $LISTEN -s $IP -p $PORT -k $PASSWD -m $METHOD
@@ -9,6 +19,22 @@
 PARAM_LIST="ip port protocol method obfs password obfsparam protoparam remarks group"
 CHECK_LIST="ip port protocol method password "
 LISTEN=${LISTEN:-20000}
+
+decode_type1(){
+	local value
+	local params_base64
+	local params_context
+	value=`base64_decode $1` || return 1
+	#Get and decode params_base64
+	params_base64=`echo "$value" | sed 's/.*\/?//'`
+	params_context=`base64_decode "$params_base64"` || return 1
+	value=`echo "$value" | sed 's/\/?.*//'`
+	echo "${value}/?${params_context}"
+	return 0
+}
+decode_type2(){
+	base64_decode "$1"
+}
 
 #value_get base64_string index
 value_get(){
@@ -57,7 +83,7 @@ param_get(){
 	local params
 	params=`value_get $1 7`
 	[ -z "$params" ] && return 0
-	params=`echo "$params" | sed "s/.*$2=//;s/&.*//"`
+	params=`echo "$params" | sed "/$2/!d;s/.*$2=//;s/&.*//"`
 	[ -z "$params" ] && return 0
 	base64_decode "$params"
 	return 0
@@ -85,19 +111,11 @@ group_get(){
 #Public functions
 #resource_decode resource
 resource_decode(){
-	local params
-	local value
-	DECODE=`base64_decode $1` || {
-	      #decode fail
-		DECODE=""
-		return 1
-	}
-	value=`echo "$DECODE" | sed 's/.*\/?//'`
-	params=`base64_decode "$value"`
-	[ $? != 0 ] && return 0
-	value=`echo "$DECODE" | sed 's/\/?.*//'`
-	DECODE="${value}/?${params}"
-	return 0
+	DECODE=`decode_type1 "$1"` && return 0
+	DECODE=`decode_type2 "$1"` && return 0
+	#decode fail
+	DECODE=""
+	return 1
 }
 
 #resource_parse resource
